services:
  legal_discovery:
    build:
      context: .
      dockerfile: apps/legal_discovery/Dockerfile
    ports:
      - "8080:5001"   # keep using http://localhost:8080
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@postgres:5432/legal_discovery}
      - CHROMA_HOST=${CHROMA_HOST:-chromadb}
      - CHROMA_PORT=${CHROMA_PORT:-8000}
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-neo4jPass123}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_started
      chromadb:
        condition: service_started
      neo4j:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./.env:/usr/src/app/.env:ro
      - ./docker_volumes/legal_discovery/uploads:/usr/src/app/uploads
      - ./docker_volumes/legal_discovery/audio_cache:/usr/src/app/audio_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=legal_discovery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker_volumes/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped

  neo4j:
    image: neo4j:5.23  # upgrade to 5.23 for latest fixes
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-neo4jPass123}
    volumes:
      - ./docker_volumes/neo4j/data:/data
    healthcheck:
      # Ensure Bolt is up AND auth works
      test: ["CMD-SHELL", "cypher-shell -a bolt://localhost:7687 -u neo4j -p \"$${NEO4J_PASSWORD:-neo4jPass123}\" \"RETURN 1\" | grep -q 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 25s
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_IMPL=postgresql
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=chroma
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./docker_volumes/chroma:/chroma_data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker_volumes/redis:/data
    restart: unless-stopped
