# factory_sense_new/herald/notification.py
from neuro_san.interfaces.coded_tool import CodedTool
import logging
from datetime import datetime, timezone
import os
from dotenv import load_dotenv
import requests

# Load environment variables
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

class ServiceNowTool(CodedTool):
    """
    ServiceNow Tool for Industrial IoT Monitoring
    Creates tickets in ServiceNow for various alerts and notifications
    """
    
    def __init__(self):
        self.logger = logging.getLogger(__name__)
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        )
        
        # ServiceNow configuration from environment variables
        self.instance = os.getenv("SERVICENOW_INSTANCE")
        self.username = os.getenv("SERVICENOW_USER")
        self.password = os.getenv("SERVICENOW_PASSWORD")
        
        # Debug logging
        logger.debug(f"ServiceNow Instance: {self.instance}")
        logger.debug(f"ServiceNow User: {self.username}")
        logger.debug("Password length: " + str(len(self.password) if self.password else 0))
        
        # Validate required environment variables
        required_vars = ["SERVICENOW_INSTANCE", "SERVICENOW_USER", "SERVICENOW_PASSWORD"]
        missing_vars = [var for var in required_vars if not os.getenv(var)]
        if missing_vars:
            self.logger.warning(f"Missing environment variables: {missing_vars}")

    def create_ticket(self, recipient: str, notification_type: str,
                     title: str, message: str, priority: str,
                     action_required: bool) -> bool:
        """Create a ticket in ServiceNow"""
        url = f"https://{self.instance}/api/now/table/incident"
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
        
        # Map priority to ServiceNow priority values (1-Critical, 2-High, 3-Medium, 4-Low)
        priority_map = {
            "critical": "1",
            "high": "2",
            "medium": "3",
            "low": "4"
        }
        
        # Prepare the ticket data
        ticket_data = {
            "short_description": title,
            "description": message,
            "priority": priority_map.get(priority.lower(), "3"),
            "impact": "2",
            "urgency": "2",
            "caller_id": recipient,
            "category": "Industrial IoT Alert",
            "subcategory": notification_type,
            "u_action_required": action_required,
            "comments": f"Alert generated by Factory Sense at {datetime.now(timezone.utc).isoformat()}"
        }

        # Log request details
        logger.debug(f"Making request to: {url}")
        logger.debug(f"Using headers: {headers}")
        
        try:
            # Make the API request
            response = requests.post(
                url,
                auth=(self.username, self.password),
                headers=headers,
                json=ticket_data,
                verify=True
            )
            response.raise_for_status()
            logger.debug(f"Response status: {response.status_code}")
            logger.debug(f"Response body: {response.text}")

            ticket_number = response.json()['result']['number']
            self.logger.info(f"Successfully created ServiceNow ticket {ticket_number}")
            return True
        except Exception as e:
            logger.error(f"Failed to create ServiceNow ticket: {str(e)}")
            return False

    def invoke(self, args, sly_data):
        """
        Main function to create ServiceNow tickets
        """
        try:
            # Extract parameters from args
            recipient = args.get("recipient")
            notification_type = args.get("notification_type")
            title = args.get("title")
            message = args.get("message")
            priority = args.get("priority", "medium")
            action_required = args.get("action_required", True)
            
            self.logger.info(f"Creating ticket for {notification_type} notification to {recipient}")
            
            # Create the ticket
            success = self.create_ticket(
                recipient=recipient,
                notification_type=notification_type,
                title=title,
                message=message,
                priority=priority,
                action_required=action_required
            )
            
            if success:
                return {
                    "success": True,
                    "recipient": recipient,
                    "notification_type": notification_type,
                    "priority": priority,
                    "timestamp": datetime.now(timezone.utc).isoformat()
                }
            else:
                return {
                    "error": "Failed to create ServiceNow ticket",
                    "recipient": recipient,
                    "timestamp": datetime.now(timezone.utc).isoformat()
                }
            
        except Exception as e:
            self.logger.error(f"Error in invoke: {e}")
            return {
                "error": str(e),
                "timestamp": datetime.now(timezone.utc).isoformat()
            }