# Copyright © 2025-2026 Cognizant Technology Solutions Corp, www.cognizant.com.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# END COPYRIGHT

import os
import sys
from importlib.resources import as_file
from importlib.resources import files
from importlib.resources.abc import Traversable
from pathlib import Path
from typing import List
from typing import Tuple

import click
from click.shell_completion import CompletionItem
from rich.console import Console

TEMPLATE_ROOT: Traversable = files("neuro_san_studio") / "templates"

# Templates can't ship as dotfiles in the wheel (some packagers skip them),
# so these names are stored without the leading dot and renamed on copy.
RENAMES = {
    "env.example": ".env.example",
    "gitignore": ".gitignore",
}

# Ordered: when multiple env keys are present, the first one wins as the
# primary provider and the rest become fallbacks. Order matches the docs'
# default-of-record (openai gpt-4o). See agent_hocon_reference.md#llm_config.
LLM_PROVIDERS: List[dict] = [
    {"env": "OPENAI_API_KEY", "class": "openai", "model_name": "gpt-5.2"},
    {"env": "ANTHROPIC_API_KEY", "class": "anthropic", "model_name": "claude-sonnet-4-6"},
]

console = Console()


def _copy_tree(src: Traversable, dst: Path, force: bool, minimal: bool) -> Tuple[int, int]:
    written = 0
    skipped = 0
    for entry in src.iterdir():
        if minimal and entry.name == "hello_world.hocon":
            continue
        target = dst / RENAMES.get(entry.name, entry.name)
        if entry.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            w, s = _copy_tree(entry, target, force, minimal)
            written += w
            skipped += s
            continue
        if target.exists() and not force:
            console.print(f"  [yellow]skip[/]  {target}")
            skipped += 1
            continue
        with as_file(entry) as src_path:
            target.write_bytes(src_path.read_bytes())
        console.print(f"  [green]write[/] {target}")
        written += 1
    return written, skipped


def _render_llm_config(detected: List[dict]) -> Tuple[str, str]:
    """Build llm_config.hocon content based on which provider env vars are set.

    Returns (file_text, human_summary). `detected` is the subset of
    LLM_PROVIDERS whose env var is present in os.environ.
    """
    header = (
        "{\n"
        "    # Shared LLM configuration referenced by agent network hocons via\n"
        '    # `include "config/llm_config.hocon"`. Generated by `ns init`.\n'
        "    # See https://github.com/cognizant-ai-lab/neuro-san/blob/main/docs/agent_hocon_reference.md#llm_config\n"
        "\n"
    )

    if len(detected) == 1:
        p = detected[0]
        body = (
            '    "llm_config": {\n'
            f'        "class": "{p["class"]}",\n'
            f'        "model_name": "{p["model_name"]}",\n'
            "    }\n"
            "}\n"
        )
        summary = f"single provider: {p['class']} (detected via {p['env']})"
        return header + body, summary

    # Either multiple providers detected, or none at all. In both cases we
    # emit a fallback list. When none were detected we also prepend a banner
    # nudging the user to set at least one key.
    if not detected:
        providers = LLM_PROVIDERS
        banner = (
            "    # No provider API key was detected in the environment at scaffold time.\n"
            "    # Set one of the following before running `ns run`, then this file works as-is:\n"
            + "".join(f"    #     export {p['env']}=...\n" for p in providers)
            + "\n"
        )
        summary = "no provider env detected — wrote fallback list for OpenAI + Anthropic"
    else:
        providers = detected
        banner = ""
        summary = "multiple providers detected: " + ", ".join(
            f"{p['class']} ({p['env']})" for p in providers
        )

    entries = ",\n".join(
        f'            {{ "class": "{p["class"]}", "model_name": "{p["model_name"]}" }}'
        for p in providers
    )
    body = (
        f'{banner}    "llm_config": {{\n'
        '        "fallbacks": [\n'
        f"{entries}\n"
        "        ]\n"
        "    }\n"
        "}\n"
    )
    return header + body, summary


@click.group(
    context_settings={"help_option_names": ["-h", "--help"]},
    help="Neuro SAN Studio command-line interface.",
)
def cli() -> None:
    pass


@cli.command(
    name="init",
    help="Scaffold a new Neuro SAN Studio project at PATH.",
)
@click.argument(
    "path",
    type=click.Path(file_okay=False, path_type=Path),
)
@click.option(
    "--force/--no-force",
    default=False,
    help="Overwrite files that already exist at the target path.",
)
@click.option(
    "--minimal/--with-example",
    default=False,
    help="Skip the hello_world example agent network.",
)
def init(path: Path, force: bool, minimal: bool) -> None:
    root = path.resolve()
    root.mkdir(parents=True, exist_ok=True)

    console.rule(f"[bold]Scaffolding Neuro SAN Studio project[/] at {root}")
    written, skipped = _copy_tree(TEMPLATE_ROOT, root, force, minimal)
    (root / "logs").mkdir(exist_ok=True)

    # Generate config/llm_config.hocon based on which provider keys are in
    # the shell environment right now (not the target dir's .env, which
    # doesn't exist yet).
    detected = [p for p in LLM_PROVIDERS if os.getenv(p["env"])]
    llm_config_text, llm_summary = _render_llm_config(detected)
    llm_target = root / "config" / "llm_config.hocon"
    llm_target.parent.mkdir(parents=True, exist_ok=True)
    if llm_target.exists() and not force:
        console.print(f"  [yellow]skip[/]  {llm_target}")
        skipped += 1
    else:
        llm_target.write_text(llm_config_text)
        console.print(f"  [green]write[/] {llm_target}   [dim]({llm_summary})[/]")
        written += 1

    console.rule("Done")
    console.print(f"  files written: [green]{written}[/]   skipped: [yellow]{skipped}[/]")
    if skipped and not force:
        console.print("  [dim]Re-run with --force to overwrite skipped files.[/]")
    console.print()
    console.print("Next steps:")
    console.print(f"  [cyan]cd {root}[/]")
    console.print("  [cyan]cp .env.example .env[/]   # then fill in API keys")
    console.print("  [cyan]ns run[/]")


@cli.command(
    name="run",
    # Forward every flag verbatim to the underlying argparse-based runner so
    # `ns run --server-http-port 8081 --client-only` behaves exactly like the
    # legacy entry point did.
    context_settings={
        "ignore_unknown_options": True,
        "allow_extra_args": True,
        "help_option_names": [],
    },
    add_help_option=False,
    help="Run the Neuro SAN Studio server and client (forwards flags to the runner).",
)
@click.argument("forwarded", nargs=-1, type=click.UNPROCESSED)
def run(forwarded: Tuple[str, ...]) -> None:
    from neuro_san_studio.run import main as run_main

    sys.argv = [sys.argv[0], *forwarded]
    run_main()


def _complete_path(ctx, param, incomplete):  # noqa: ARG001
    # click.UNPROCESSED carries no type info, so the shell completer gets no
    # file/dir hints by default. Returning a CompletionItem of type "file"
    # delegates to zsh's `_path_files -f`, which descends into directories.
    return [CompletionItem(incomplete, type="file")]


@cli.command(
    name="validate",
    # Forward every flag verbatim to the underlying argparse-based validator so
    # `ns validate path/to/agent.hocon --verbose` behaves exactly like
    # `python -m neuro_san.client.hocon_validator_cli ...`.
    context_settings={
        "ignore_unknown_options": True,
        "allow_extra_args": True,
        "help_option_names": [],
    },
    add_help_option=False,
    help="Validate a HOCON agent network file (forwards flags to neuro-san's validator).",
)
@click.argument("forwarded", nargs=-1, type=click.UNPROCESSED, shell_complete=_complete_path)
def validate(forwarded: Tuple[str, ...]) -> None:
    from neuro_san.client.hocon_validator_cli import HoconValidatorCli

    sys.argv = [sys.argv[0], *forwarded]
    sys.exit(HoconValidatorCli().main())


if __name__ == "__main__":
    cli()
