---
name: Checkmarx One

on:
    schedule:
        # M-F at 3:00 am UTC (offset from neuro-san and neuro-san-ui)
        - cron: "0 3 * * 1-5"
    workflow_dispatch:
    release:
        types:
            - published

jobs:
    checkmarx:
        # 1.0.13
        uses: cognizant-ai-lab/build-common/.github/workflows/_checkmarx.yml@e11ab4d3725a79bd8b28c3f7fb0785615290cf24
        with:
            # 1.0.13
            build-common-ref: "e11ab4d3725a79bd8b28c3f7fb0785615290cf24"
            base-uri: ${{ vars.CX_BASE_URI }}
            cx-tenant: ${{ vars.CX_TENANT }}
            cx-client-id: ${{ vars.CX_CLIENT_ID }}
            scan-params: '--sast-preset-name "Checkmarx Default" --threshold "sast-critical=1;sast-high=1"'
        secrets:
            CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        permissions:
            contents: write
            security-events: write
