name: Publish to PyPI

permissions:
    contents: read

on:
  release:
    types: [published]  # Trigger only when a GitHub Release is published.

jobs:
  publish:
    name: Build and Publish
    # don't run this job in sync'd clones
    if: github.repository == 'cognizant-ai-lab/neuro-san-studio'
    runs-on: ubuntu-latest
    environment: pypi  # Match this to your configured GitHub Environment.
    permissions:
      id-token: write  # Mandatory for PyPI Trusted Publishing
      contents: read   # Required for actions/checkout

    steps:
      # v6.0.2
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Build and publish package
        # 1.0.10
        uses: cognizant-ai-lab/build-common/actions/publish-pypi@cb254b1336a6a6034008eab4d5a94a9c034fa89c
        with:
          python-version: '3.10'

      - name: Notify Slack
        if: ${{ !cancelled() }}
        # 1.0.10
        uses: cognizant-ai-lab/build-common/actions/slack-notify@cb254b1336a6a6034008eab4d5a94a9c034fa89c
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
