name: AND Smoke Tests

permissions:
    contents: read

on:
  schedule:
    - cron: '0 12 * * *'  # 12:00 PM UTC = 4:00 AM PT (standard)
  workflow_dispatch:      # enables manual triggering

jobs:
  and-smoke-test:
    runs-on: ubuntu-latest

    # Job-level ENV shared by all steps
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PYTHONPATH: "."
      AGENT_TOOL_PATH: "coded_tools/"
      AGENT_MANIFEST_FILE: "registries/manifest.hocon"
      AGENT_TEMPORARY_NETWORK_UPDATE_PERIOD_SECONDS: 5

    # don't run this job in sync'd clones
    if: github.repository == 'cognizant-ai-lab/neuro-san-studio'
    container:
      image: python:3.13-slim

    steps:
      # v4.3.1
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Install dependencies
        shell: bash
        run: |
          apt-get update && apt-get install --yes make curl
          make install

      - name: Show installed packages
        shell: bash
        run: |
          source venv/bin/activate
          pip freeze

      - name: Start server & run AND smoke tests & print server log if any failure
        shell: bash
        run: |
          source venv/bin/activate
          build_scripts/server_start.sh

          if ! pytest --capture=no --verbose -m "integration_and_smoke" --timer-top-n 100; then
            echo "===================================================="
            echo "=== Server Log ==="
            cat logs/server.log || echo "(no server.log found)"
            echo "===================================================="
            exit 1
          fi

      - name: Notify Slack
        if: ${{ !cancelled() }}
        # 1.0.0
        uses: cognizant-ai-lab/build-common/actions/slack-notify@455db3cc40e9ed6a0fb9bbaf8188888c1ae315c2
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
