name: Sync fork with upstream

on:
  schedule:
    - cron: '0 0 * * 1'  # Run automatically every Monday at 00:00 UTC (09:00 JST)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/cognizant-ai-lab/neuro-san-studio.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into fork's main
        run: |
          git checkout main
          git merge --no-edit upstream/main || echo "No changes to merge"

      - name: Push changes to fork
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
