name: Sync fork with upstream

on:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜0:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/cognizant-ai-lab/neuro-san-studio.git
          git fetch upstream

      - name: Create sync-upstream branch and merge
        run: |
          git checkout -b sync-upstream origin/main
          git merge upstream/main --no-edit || true
          git push origin sync-upstream --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-upstream
          base: main
          title: "🔄 Weekly Sync with Upstream"
          body: |
            This PR merges upstream changes into `main`. Please resolve any conflicts manually if needed.
          commit-message: "chore: merge upstream into main"
          delete-branch: false
          assignees: y107818
